include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: true
    directives_ordering: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    public_member_api_docs: false
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/oss_licenses.dart"
    - "**/firebase_options.dart"
  errors:
    invalid_annotation_target: ignore
