name: scenarioshelf
version: 1.0.0+1
publish_to: none
description: TRPG通過シナリオ記録サービス

environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  
  # Design
  cupertino_icons: 1.0.6
  google_fonts: 6.1.0

  # Firebase
  firebase_core: 2.25.5
  firebase_analytics: 10.8.7
  firebase_crashlytics: 3.4.16
  firebase_auth: 4.17.6
  google_sign_in: 6.2.1
  cloud_firestore: 4.15.6

  # State Management
  flutter_hooks: 0.20.5
  hooks_riverpod: 2.4.10
  riverpod_annotation: 2.3.4
  freezed_annotation: 2.4.1

  # Other
  go_router: 13.2.0
  intl: 0.19.0
  logger: 2.0.2+1
  app_tracking_transparency: 2.0.4

dev_dependencies:
  flutter_test: 
    sdk: flutter
  
  # Generator
  build_runner: 2.4.8
  freezed: 2.4.7
  json_serializable: 6.7.1
  riverpod_generator: 2.3.11
  flutter_launcher_icons: 0.13.1
  flutter_oss_licenses: 2.0.1
  flutter_gen_runner: 5.4.0
  
  # Linter
  flutter_lints: 3.0.1
  custom_lint: 0.6.2
  very_good_analysis: 5.1.0
  riverpod_lint: 2.3.9
  
  # Other
  import_sorter: 4.6.0

  # build_runner の実行コマンド
  # fvm flutter packages pub run build_runner build --delete-conflicting-outputs
  # fvm flutter packages pub run build_runner watch --delete-conflicting-outputs

  # oss_licenses.dart の生成コマンド（パッケージを追加したら実行する）
  # fvm flutter pub run flutter_oss_licenses:generate.dart -o lib/constants/oss_licenses.dart
  
flutter: 
  uses-material-design: true
  assets:
    - assets/images/logos/

import_sorter:
  comments: false
  ignored_files:
    - \/lib\/*\/*.freezed.dart
    - \/lib\/*\/*.g.dart
    - \/lib\/*\/oss_licenses.dart
    - \/lib\/*\/firebase_options.dart

  # 実行コマンド
  # fvm flutter pub run import_sorter:main

flutter_icons:
  android: "launcher_icon"
  min_sdk_android: 21
  adaptive_icon_background: "#FFC966"
  ios: true
  remove_alpha_ios: true

  # 実行コマンド
  # fvm flutter pub run flutter_launcher_icons:main

flutter_gen:
  output: lib/constants/assets/gen/
  line_length: 200

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
