part of 'app_color.dart';

class _AppMaterialLight extends ColorScheme {
  const _AppMaterialLight()
      : super(
          brightness: Brightness.light,
          primary: const Color(0xFF7C4E29),
          onPrimary: const Color(0xFFFFFFFF),
          primaryContainer: const Color(0xFFFFDCC4),
          onPrimaryContainer: const Color(0xFF2F1400),
          secondary: const Color(0xFF745945),
          onSecondary: const Color(0xFFFFFFFF),
          secondaryContainer: const Color(0xFFFFDCC4),
          onSecondaryContainer: const Color(0xFF2A1708),
          tertiary: const Color(0xFF5E6136),
          onTertiary: const Color(0xFFFFFFFF),
          tertiaryContainer: const Color(0xFFE3E7AF),
          onTertiaryContainer: const Color(0xFF1A1D00),
          error: const Color(0xFFff3300),
          errorContainer: const Color(0xFFFFDAD6),
          onError: const Color(0xFFFFFFFF),
          onErrorContainer: const Color(0xFF410002),
          surface: const Color(0xFFFFFBFF),
          onSurface: const Color(0xFF201A17),
          surfaceContainerLowest: const Color(0xFFf0dfd6),
          surfaceContainerLow: const Color(0xFFf5e5dc),
          surfaceContainer: const Color(0xFFfbebe1),
          surfaceContainerHigh: const Color(0xFFfff1e9),
          surfaceContainerHighest: const Color(0xFFffffff),
          onSurfaceVariant: const Color(0xFF52443B),
          outline: const Color(0xFF84746A),
          onInverseSurface: const Color(0xFFFBEEE8),
          inverseSurface: const Color(0xFF362F2B),
          inversePrimary: const Color(0xFFFFB781),
          shadow: const Color(0xFF000000),
          surfaceTint: const Color(0xFF924C00),
          outlineVariant: const Color(0xFFD6C3B7),
          scrim: const Color(0xFF000000),
        );
}

class _AppMaterialDark extends ColorScheme {
  const _AppMaterialDark()
      : super(
          brightness: Brightness.dark,
          primary: const Color(0xFFFFB781),
          onPrimary: const Color(0xFF4E2600),
          primaryContainer: const Color(0xFF6F3800),
          onPrimaryContainer: const Color(0xFFFFDCC4),
          secondary: const Color(0xFFE4BFA7),
          onSecondary: const Color(0xFF422B1A),
          secondaryContainer: const Color(0xFF5B412F),
          onSecondaryContainer: const Color(0xFFFFDCC4),
          tertiary: const Color(0xFFC7CA95),
          onTertiary: const Color(0xFF2F330C),
          tertiaryContainer: const Color(0xFF464A20),
          onTertiaryContainer: const Color(0xFFE3E7AF),
          error: const Color(0xFFff3300),
          errorContainer: const Color(0xFF93000A),
          onError: const Color(0xFF690005),
          onErrorContainer: const Color(0xFFFFDAD6),
          surface: const Color(0xFF201A17),
          onSurface: const Color(0xFFECE0DA),
          surfaceContainerLowest: const Color(0xFF140d08),
          surfaceContainerLow: const Color(0xFF221a14),
          surfaceContainer: const Color(0xFF261e18),
          surfaceContainerHigh: const Color(0xFF312822),
          surfaceContainerHighest: const Color(0xFF3c332d),
          onSurfaceVariant: const Color(0xFFD6C3B7),
          outline: const Color(0xFF9F8D82),
          onInverseSurface: const Color(0xFF201A17),
          inverseSurface: const Color(0xFFECE0DA),
          inversePrimary: const Color(0xFF924C00),
          shadow: const Color(0xFF000000),
          surfaceTint: const Color(0xFFFFB781),
          outlineVariant: const Color(0xFF52443B),
          scrim: const Color(0xFF000000),
        );
}
